version: '3'

services:

  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - diploma-server

  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: VA2216w1!
    ports:
      - 1433:1433

  diploma-server:
    restart: always
    image: maven:3.5-jdk-8
    working_dir: /diploma-server/
    volumes:
      - ./server:/diploma-server
    ports:
      - 8085:8085
    environment:
      - DB_URL=jdbc:sqlserver://mssql:1433;database=master
      - DB_USER=sa
      - DB_PASSWORD=VA2216w1!
      - DB_DIALECT=org.hibernate.dialect.SQLServer2012Dialect
      - DB_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SERVER_PORT=8085
    command: java -jar /diploma-server/diploma-server.jar
    depends_on:
      - mssql
